# Generated by Django 5.2.11 on 2026-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("supplier", "Supplier"),
                    ("provider", "Service Provider"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
